name: Build

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Plugins
        run: |
          chmod +x gradlew
          ./gradlew makePlugins

      - name: Deploy to builds branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./builds
          publish_branch: builds
          force_orphan: true
